AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  demo_xray
  Sample SAM Template for demo_xray

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20
    Tracing: Active
  Api:
    TracingEnabled: True

Resources:
  DemoXrayAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Auth:
        DefaultAuthorizer: AWS_IAM

  DemoXrayFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: DemoXrayFunction
      CodeUri: DemoXrayFunction
      Handler: xray.App::handleRequest
      FunctionUrlConfig:
        AuthType: AWS_IAM
      Role: arn:aws:iam::511854313241:role/CR_demo-xray-java-Role
      Runtime: java8.al2
      Architectures:
        - x86_64
      MemorySize: 512
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1 # More info about tiered compilation https://aws.amazon.com/blogs/compute/optimizing-aws-lambda-function-performance-for-java/
      Events:
        DemoXrayGet:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref DemoXrayAPI
            Path: /xray
            Method: get
        DemoXrayPost:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref DemoXrayAPI
            Path: /xray
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  DemoXrayApiUrl:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${DemoXrayAPI}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  DemoXrayFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt DemoXrayFunction.Arn
  DemoXrayFunctionIamRole:
    Description: "explicit IAM Role created for demo-xray function"
    Value: arn:aws:iam::511854313241:role/CR_demo-xray-java-Role
